# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.4 on Wed Jan 25 16:04:41 2023
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
from SELKIELogger.Config import SourceTypes

# end wxGlade


class SLCChooseType(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: SLCChooseType.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.SetTitle(_("SLConfig: Source Type"))

        _ct = wx.BoxSizer(wx.VERTICAL)

        sizer_2 = wx.StaticBoxSizer(
            wx.StaticBox(self, wx.ID_ANY, _("Source Type")), wx.VERTICAL
        )
        _ct.Add(sizer_2, 1, wx.EXPAND, 0)

        label_1 = wx.StaticText(self, wx.ID_ANY, _("Select data source type:"))
        sizer_2.Add(label_1, 0, wx.ALL, 2)

        self.ctType = wx.ComboBox(
            self, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN | wx.CB_SORT
        )
        sizer_2.Add(self.ctType, 0, wx.ALL | wx.EXPAND, 2)

        _ctLower = wx.StdDialogButtonSizer()
        _ct.Add(_ctLower, 0, wx.ALIGN_RIGHT | wx.ALL, 4)

        self.btnCTOK = wx.Button(self, wx.ID_OK, "")
        self.btnCTOK.SetDefault()
        _ctLower.AddButton(self.btnCTOK)

        self.btnCTCancel = wx.Button(self, wx.ID_CANCEL, "")
        _ctLower.AddButton(self.btnCTCancel)

        _ctLower.Realize()

        self.SetSizer(_ct)
        _ct.Fit(self)

        self.SetAffirmativeId(self.btnCTOK.GetId())
        self.SetEscapeId(self.btnCTCancel.GetId())

        self.Layout()
        self.Centre()
        sources = []
        for st in SourceTypes:
            if SourceTypes[st][2]:
                # SourceTypes[x][2] is the "show by default" flag
                # Hidden types are still recognised and handled, but won't be
                # offered to the user in this dialog
                caption = f"{st}: {SourceTypes[st][1]}"
                sources.extend([caption])
        self.ctType.Append(sources)
        # end wxGlade


# end of class SLCChooseType
