# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.4 on Tue Jan 24 17:09:36 2023
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class SLCChooseType(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: SLCChooseType.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.SetTitle(_("SLConfig: Source Type"))

        _ct = wx.BoxSizer(wx.VERTICAL)

        sizer_2 = wx.StaticBoxSizer(
            wx.StaticBox(self, wx.ID_ANY, _("Source Type")), wx.VERTICAL
        )
        _ct.Add(sizer_2, 1, wx.EXPAND, 0)

        label_1 = wx.StaticText(self, wx.ID_ANY, _("Select data source type:"))
        sizer_2.Add(label_1, 0, wx.ALL, 2)

        self.ctType = wx.ComboBox(
            self,
            wx.ID_ANY,
            choices=[
                _("DW: Datawell Wave Buoy"),
                _("GPS: uBlox GPS Module (or compatible)"),
                _("I2C: I2C connected sensors"),
                _("NMEA: Classic NMEA serial interface"),
                _("N2K: Actisense NMEA 2000 USB Gateway (or compatble)"),
                _("SL: Hardware outputting SELKIELogger formatted messages"),
                _("SERIAL: Generic serial device support (record only)"),
                _("TCP: Generic TCP network data source (record only)"),
                _("TIMER: Software defined timestamp generator"),
                _("LPMS: LP Research IMU devices"),
                _("MQTT: Subscribe to MQTT network broker (inc. Victron devices)"),
            ],
            style=wx.CB_DROPDOWN | wx.CB_SORT,
        )
        sizer_2.Add(self.ctType, 0, wx.ALL | wx.EXPAND, 2)

        self.description = wx.NewId()
        lblDescription = wx.StaticText(self, self.description, "")
        sizer_2.Add(lblDescription, 2, wx.ALL, 2)

        _ctLower = wx.StdDialogButtonSizer()
        _ct.Add(_ctLower, 0, wx.ALIGN_RIGHT | wx.ALL, 4)

        self.btnCTOK = wx.Button(self, wx.ID_OK, "")
        self.btnCTOK.SetDefault()
        _ctLower.AddButton(self.btnCTOK)

        self.btnCTCancel = wx.Button(self, wx.ID_CANCEL, "")
        _ctLower.AddButton(self.btnCTCancel)

        _ctLower.Realize()

        self.SetSizer(_ct)
        _ct.Fit(self)

        self.SetAffirmativeId(self.btnCTOK.GetId())
        self.SetEscapeId(self.btnCTCancel.GetId())

        self.Layout()
        self.Centre()
        # end wxGlade


# end of class SLCChooseType
