# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.4 on Wed Jan 25 16:04:41 2023
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
from SELKIELogger.Config import SLCDW

# end wxGlade


class SLCDWConfig(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: SLCDWConfig.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.SetSize((550, 400))
        self.SetTitle(_("SLConfig: Datawell receiver"))

        _cg = wx.BoxSizer(wx.VERTICAL)

        explanation = wx.StaticText(
            self,
            wx.ID_ANY,
            _(
                "Parse data from a Datawell wavebuoy receiver, optionally including spectral data or recording a copy of raw data for later analysis in other software.\n\nProvide a reference tag and the network connection details below"
            ),
            style=wx.ALIGN_LEFT,
        )
        explanation.SetMinSize((-1, 70))
        explanation.Wrap(500)
        _cg.Add(explanation, 0, wx.ALL | wx.EXPAND, 2)

        grid_sizer_1 = wx.FlexGridSizer(6, 2, 2, 2)
        _cg.Add(grid_sizer_1, 1, wx.ALL | wx.EXPAND, 2)

        _ctTag = wx.StaticText(self, wx.ID_ANY, _("Tag:"))
        grid_sizer_1.Add(_ctTag, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL | wx.EXPAND, 2)

        self.tag = wx.TextCtrl(self, wx.ID_ANY, "")
        grid_sizer_1.Add(self.tag, 1, wx.ALL | wx.EXPAND, 2)

        _ctName = wx.StaticText(self, wx.ID_ANY, _("Source Name:"))
        grid_sizer_1.Add(_ctName, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL | wx.EXPAND, 2)

        self.name = wx.TextCtrl(self, wx.ID_ANY, "")
        grid_sizer_1.Add(self.name, 1, wx.ALL | wx.EXPAND, 2)

        _ctSourceNumber = wx.StaticText(
            self, wx.ID_ANY, _("Source Number:\nDefault range: 0x60...0x67")
        )
        grid_sizer_1.Add(
            _ctSourceNumber, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL | wx.EXPAND, 2
        )

        self.sourcenum = wx.SpinCtrl(self, wx.ID_ANY, "96", min=0, max=120)
        grid_sizer_1.Add(self.sourcenum, 0, wx.ALL, 2)

        _ctHost = wx.StaticText(self, wx.ID_ANY, _("Host:"))
        grid_sizer_1.Add(_ctHost, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL | wx.EXPAND, 2)

        self.host = wx.TextCtrl(self, wx.ID_ANY, "")
        self.host.SetToolTip(_("e.g. /dev/ttyUSB0, /dev/serial/by-id/xxxxxx"))
        grid_sizer_1.Add(self.host, 1, wx.ALL | wx.EXPAND, 2)

        _ctTimeout = wx.StaticText(self, wx.ID_ANY, _("Timeout (s):"))
        grid_sizer_1.Add(
            _ctTimeout, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL | wx.EXPAND, 2
        )

        self.timeout = wx.SpinCtrl(self, wx.ID_ANY, "100", min=60, max=1800)
        grid_sizer_1.Add(self.timeout, 0, wx.ALL, 2)

        self.spectrum = wx.CheckBox(self, wx.ID_ANY, _("Parse spectral information"))
        grid_sizer_1.Add(self.spectrum, 0, wx.ALL, 2)

        self.raw = wx.CheckBox(self, wx.ID_ANY, _("Keep copy of raw data"))
        grid_sizer_1.Add(self.raw, 0, wx.ALL, 2)

        sizer_2 = wx.StdDialogButtonSizer()
        _cg.Add(sizer_2, 0, wx.ALIGN_RIGHT | wx.ALL, 4)

        self.button_OK = wx.Button(self, wx.ID_OK, "")
        self.button_OK.SetDefault()
        sizer_2.AddButton(self.button_OK)

        self.button_CANCEL = wx.Button(self, wx.ID_CANCEL, "")
        sizer_2.AddButton(self.button_CANCEL)

        sizer_2.Realize()

        grid_sizer_1.AddGrowableCol(0)
        grid_sizer_1.AddGrowableCol(1)

        self.SetSizer(_cg)

        self.SetAffirmativeId(self.button_OK.GetId())
        self.SetEscapeId(self.button_CANCEL.GetId())

        self.Layout()
        self.sourcenum.SetBase(16)
        self.sourcenum.SetValue(0x60)
        self.timeout.SetValue(180)

        self.generateSource = lambda: SLCDW(
            tag=self.tag.GetValue(),
            timeout=int(self.timeout.GetValue()),
            host=self.host.GetValue(),
            name=self.name.GetValue(),
            sourcenum=self.sourcenum.GetValue(),
            spectrum=self.spectrum.GetValue(),
            raw=self.raw.GetValue(),
        )

        def updateFromSource(s):
            self.tag.SetValue(s.tag)
            self.timeout.SetValue(str(s.timeout))
            self.host.SetValue(s.host)
            self.name.SetValue(s.name)
            self.sourcenum.SetValue(s.sourcenum)
            self.spectrum.SetValue(s.spectrum)
            self.raw.SetValue(s.raw)

        self.updateFromSource = updateFromSource
        # end wxGlade


# end of class SLCDWConfig
