# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.4 on Wed Jan 25 17:27:39 2023
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
from SELKIELogger.Config import SLCUnknown

# end wxGlade


class SLCGeneric(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: SLCGeneric.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.SetSize((400, 450))
        self.SetTitle(_("SLConfig: Generic/Unknown Source Type"))

        _cg = wx.BoxSizer(wx.VERTICAL)

        explanation = wx.StaticText(
            self,
            wx.ID_ANY,
            _(
                'This source type is not yet supported by the configuration tool.\n\nType specific values can be edited at the bottom of the form, in key="value" form.'
            ),
            style=wx.ALIGN_LEFT,
        )
        explanation.SetMinSize((-1, 70))
        explanation.Wrap(380)
        _cg.Add(explanation, 0, wx.ALL | wx.EXPAND, 2)

        grid_sizer_1 = wx.FlexGridSizer(6, 1, 2, 2)
        _cg.Add(grid_sizer_1, 1, wx.ALL | wx.EXPAND, 2)

        _ctTag = wx.StaticText(self, wx.ID_ANY, _("Tag:"))
        grid_sizer_1.Add(_ctTag, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL | wx.EXPAND, 2)

        self.tag = wx.TextCtrl(self, wx.ID_ANY, "")
        grid_sizer_1.Add(self.tag, 1, wx.ALL | wx.EXPAND, 2)

        _ctType = wx.StaticText(self, wx.ID_ANY, _("Source Type:"))
        grid_sizer_1.Add(_ctType, 0, wx.ALL, 2)

        self.type = wx.TextCtrl(self, wx.ID_ANY, "")
        grid_sizer_1.Add(self.type, 0, wx.ALL | wx.EXPAND, 2)

        _ctParams = wx.StaticText(self, wx.ID_ANY, _("Type Specific Parameters:"))
        grid_sizer_1.Add(_ctParams, 0, wx.ALL, 2)

        self.parameters = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_MULTILINE)
        self.parameters.SetMinSize((-1, 200))
        grid_sizer_1.Add(self.parameters, 4, wx.ALL | wx.EXPAND, 2)

        sizer_2 = wx.StdDialogButtonSizer()
        _cg.Add(sizer_2, 0, wx.ALIGN_RIGHT | wx.ALL, 4)

        self.button_OK = wx.Button(self, wx.ID_OK, "")
        self.button_OK.SetDefault()
        sizer_2.AddButton(self.button_OK)

        self.button_CANCEL = wx.Button(self, wx.ID_CANCEL, "")
        sizer_2.AddButton(self.button_CANCEL)

        sizer_2.Realize()

        grid_sizer_1.AddGrowableCol(0)

        self.SetSizer(_cg)

        self.SetAffirmativeId(self.button_OK.GetId())
        self.SetEscapeId(self.button_CANCEL.GetId())

        self.Layout()
        self.generateSource = lambda: SLCUnknown(
            tag=self.tag.GetValue(),
            sourcetype=self.type.GetValue(),
            params=self.parameters.GetValue().split("\n"),
        )

        def updateFromSource(s):
            self.tag.SetValue(s.tag)
            self.type.SetValue(s.sourcetype)
            self.parameters.SetValue("\n".join(s.params))

        self.updateFromSource = updateFromSource
        # end wxGlade


# end of class SLCGeneric
