# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.4 on Wed Jan 25 16:04:41 2023
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
from SELKIELogger.Config import SLCMP

# end wxGlade


class SLCMPConfig(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: SLCMPConfig.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.SetSize((400, 330))
        self.SetTitle(_("SLConfig: SL Source Type"))

        _cg = wx.BoxSizer(wx.VERTICAL)

        explanation = wx.StaticText(
            self,
            wx.ID_ANY,
            _(
                "Devices that output the SELKIELogger protocol will provide their own source name, number, and channel mapping details.\n\nProvide a reference tag and the hardware connection details below"
            ),
            style=wx.ALIGN_LEFT,
        )
        explanation.SetMinSize((-1, 70))
        explanation.Wrap(380)
        _cg.Add(explanation, 0, wx.ALL | wx.EXPAND, 2)

        grid_sizer_1 = wx.FlexGridSizer(6, 1, 2, 2)
        _cg.Add(grid_sizer_1, 1, wx.ALL | wx.EXPAND, 2)

        _ctTag = wx.StaticText(self, wx.ID_ANY, _("Tag:"))
        grid_sizer_1.Add(_ctTag, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL | wx.EXPAND, 2)

        self.tag = wx.TextCtrl(self, wx.ID_ANY, "")
        grid_sizer_1.Add(self.tag, 1, wx.ALL | wx.EXPAND, 2)

        _ctPort = wx.StaticText(
            self,
            wx.ID_ANY,
            _("Port: (e.g. /dev/ttyUSB0, /dev/serial/by-id/xxx, COM1:)"),
        )
        grid_sizer_1.Add(_ctPort, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL | wx.EXPAND, 2)

        self.port = wx.TextCtrl(self, wx.ID_ANY, "")
        grid_sizer_1.Add(self.port, 1, wx.ALL | wx.EXPAND, 2)

        _ctBaud = wx.StaticText(self, wx.ID_ANY, _("Baud rate:"))
        grid_sizer_1.Add(_ctBaud, 0, wx.ALL, 2)

        self.baud = wx.TextCtrl(self, wx.ID_ANY, _("115200"))
        grid_sizer_1.Add(self.baud, 0, wx.ALL | wx.EXPAND, 2)

        sizer_2 = wx.StdDialogButtonSizer()
        _cg.Add(sizer_2, 0, wx.ALIGN_RIGHT | wx.ALL, 4)

        self.button_OK = wx.Button(self, wx.ID_OK, "")
        self.button_OK.SetDefault()
        sizer_2.AddButton(self.button_OK)

        self.button_CANCEL = wx.Button(self, wx.ID_CANCEL, "")
        sizer_2.AddButton(self.button_CANCEL)

        sizer_2.Realize()

        grid_sizer_1.AddGrowableCol(0)

        self.SetSizer(_cg)

        self.SetAffirmativeId(self.button_OK.GetId())
        self.SetEscapeId(self.button_CANCEL.GetId())

        self.Layout()
        self.generateSource = lambda: SLCMP(
            tag=self.tag.GetValue(),
            port=self.port.GetValue(),
            baud=int(self.baud.GetValue()),
        )

        def updateFromSource(s):
            self.tag.SetValue(s.tag)
            self.port.SetValue(s.port)
            self.baud.SetValue(str(s.baud))

        self.updateFromSource = updateFromSource
        # end wxGlade


# end of class SLCMPConfig
