# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.4 on Tue Jan 24 17:09:36 2023
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
from SELKIELogger.Config import SLCNet

# end wxGlade


class SLCNetConfig(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: SLCNetConfig.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.SetTitle(_("SLConfig: Generic Serial Source Type"))

        _cg = wx.BoxSizer(wx.VERTICAL)

        explanation = wx.StaticText(
            self,
            wx.ID_ANY,
            _(
                "Support for recording raw data from a TCP port.\nThis data will not be interpreted in anyway, but will be available to extract later.\n\nProvide a reference tag and the network connection details below"
            ),
            style=wx.ALIGN_LEFT,
        )
        explanation.SetMinSize((-1, 70))
        _cg.Add(explanation, 0, wx.ALL | wx.EXPAND, 2)

        grid_sizer_1 = wx.FlexGridSizer(7, 2, 2, 2)
        _cg.Add(grid_sizer_1, 1, wx.ALL | wx.EXPAND, 2)

        _ctTag = wx.StaticText(self, wx.ID_ANY, _("Tag:"))
        grid_sizer_1.Add(_ctTag, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL | wx.EXPAND, 2)

        self.tag = wx.TextCtrl(self, wx.ID_ANY, "")
        grid_sizer_1.Add(self.tag, 1, wx.ALL | wx.EXPAND, 2)

        _ctName = wx.StaticText(self, wx.ID_ANY, _("Source Name:"))
        grid_sizer_1.Add(_ctName, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL | wx.EXPAND, 2)

        self.name = wx.TextCtrl(self, wx.ID_ANY, "")
        grid_sizer_1.Add(self.name, 1, wx.ALL | wx.EXPAND, 2)

        _ctSourceNumber = wx.StaticText(
            self, wx.ID_ANY, _("Source Number:\nDefault range: 96...110")
        )
        grid_sizer_1.Add(
            _ctSourceNumber, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL | wx.EXPAND, 2
        )

        self.sourcenum = wx.SpinCtrl(self, wx.ID_ANY, "96", min=0, max=120)
        grid_sizer_1.Add(self.sourcenum, 0, wx.ALL, 2)

        _ctHost = wx.StaticText(self, wx.ID_ANY, _("Host:"))
        grid_sizer_1.Add(_ctHost, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL | wx.EXPAND, 2)

        self.host = wx.TextCtrl(self, wx.ID_ANY, "")
        self.host.SetToolTip(_("e.g. /dev/ttyUSB0, /dev/serial/by-id/xxxxxx"))
        grid_sizer_1.Add(self.host, 1, wx.ALL | wx.EXPAND, 2)

        _ctPort = wx.StaticText(self, wx.ID_ANY, _("Port:"))
        grid_sizer_1.Add(_ctPort, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL | wx.EXPAND, 2)

        self.port = wx.SpinCtrl(self, wx.ID_ANY, "100", min=1, max=65534)
        grid_sizer_1.Add(self.port, 0, wx.ALL, 2)

        _ctPSize = wx.StaticText(self, wx.ID_ANY, _("Packet size range:"))
        grid_sizer_1.Add(_ctPSize, 0, wx.ALL, 2)

        psizes = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_1.Add(psizes, 1, wx.ALL | wx.EXPAND, 1)

        self.minpacketsize = wx.SpinCtrl(self, wx.ID_ANY, "10", min=0, max=1024)
        self.minpacketsize.SetMinSize((160, -1))
        psizes.Add(self.minpacketsize, 0, wx.ALL, 2)

        _ctTo = wx.StaticText(self, wx.ID_ANY, _("to"))
        psizes.Add(_ctTo, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 5)

        self.maxpacketsize = wx.SpinCtrl(self, wx.ID_ANY, "100", min=0, max=1024)
        self.maxpacketsize.SetMinSize((160, -1))
        psizes.Add(self.maxpacketsize, 0, wx.ALL, 2)

        _ctFreq = wx.StaticText(self, wx.ID_ANY, _("Frequency"))
        grid_sizer_1.Add(_ctFreq, 0, wx.ALL, 2)

        self.frequency = wx.SpinCtrl(self, wx.ID_ANY, "10", min=0, max=20)
        grid_sizer_1.Add(self.frequency, 0, wx.ALL, 2)

        sizer_2 = wx.StdDialogButtonSizer()
        _cg.Add(sizer_2, 0, wx.ALIGN_RIGHT | wx.ALL, 4)

        self.button_OK = wx.Button(self, wx.ID_OK, "")
        self.button_OK.SetDefault()
        sizer_2.AddButton(self.button_OK)

        self.button_CANCEL = wx.Button(self, wx.ID_CANCEL, "")
        sizer_2.AddButton(self.button_CANCEL)

        sizer_2.Realize()

        self.SetSizer(_cg)
        _cg.Fit(self)

        self.SetAffirmativeId(self.button_OK.GetId())
        self.SetEscapeId(self.button_CANCEL.GetId())

        self.Layout()
        self.generateSource = lambda: SLCNet(
            tag=self.tag.GetValue(),
            port=int(self.port.GetValue()),
            host=self.host.GetValue(),
            name=self.name.GetValue(),
            sourcenum=self.sourcenum.GetValue(),
            minbytes=self.minpacketsize.GetValue(),
            maxbytes=self.maxpacketsize.GetValue(),
            frequency=self.frequency.GetValue(),
        )

        def updateFromSource(s):
            self.tag.SetValue(s.tag)
            self.port.SetValue(str(s.port))
            self.host.SetValue(s.host)
            self.name.SetValue(s.name)
            self.sourcenum.SetValue(s.sourcenum)
            self.minpacketsize.SetValue(s.minbytes)
            self.maxpacketsize.SetValue(s.maxbytes)
            self.frequency.SetValue(s.frequency)

        self.updateFromSource = updateFromSource
        # end wxGlade


# end of class SLCNetConfig
