# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.4 on Tue Jan 24 17:09:36 2023
#

import wx

# begin wxGlade: dependencies
import wx.grid

# end wxGlade

# begin wxGlade: extracode
from .SLCUIHandlers import *

# end wxGlade


class SLConfigGUIMain(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: SLConfigGUIMain.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((800, 600))
        self.SetTitle(_("SLConfig"))

        self._mw = wx.SplitterWindow(self, wx.ID_ANY)
        self._mw.SetMinimumPaneSize(20)

        self._mw_controls = wx.Panel(self._mw, wx.ID_ANY)

        _mw_c_sizer = wx.FlexGridSizer(12, 1, 2, 0)

        _mw_c_sizer.Add((0, 25), 0, 0, 0)

        lblFile = wx.StaticText(self._mw_controls, wx.ID_ANY, _("Import / Export"))
        lblFile.SetFont(
            wx.Font(
                11,
                wx.FONTFAMILY_DEFAULT,
                wx.FONTSTYLE_NORMAL,
                wx.FONTWEIGHT_BOLD,
                0,
                "",
            )
        )
        _mw_c_sizer.Add(lblFile, 0, wx.EXPAND, 0)

        _mw_File = wx.GridSizer(1, 2, 2, 2)
        _mw_c_sizer.Add(_mw_File, 1, wx.EXPAND, 0)

        self.btnLoadFile = wx.Button(self._mw_controls, wx.ID_ANY, _("&Load File..."))
        _mw_File.Add(self.btnLoadFile, 1, wx.ALL | wx.EXPAND, 2)

        self.btnSaveFile = wx.Button(self._mw_controls, wx.ID_ANY, _("&Save File..."))
        _mw_File.Add(self.btnSaveFile, 1, wx.ALL | wx.EXPAND, 2)

        _mw_c_sizer.Add((0, 25), 0, 0, 0)

        lblGenSet = wx.StaticText(self._mw_controls, wx.ID_ANY, _("General Settings"))
        lblGenSet.SetFont(
            wx.Font(
                11,
                wx.FONTFAMILY_DEFAULT,
                wx.FONTSTYLE_NORMAL,
                wx.FONTWEIGHT_BOLD,
                0,
                "",
            )
        )
        _mw_c_sizer.Add(lblGenSet, 0, wx.EXPAND, 0)

        _mw_gen_settings = wx.GridSizer(4, 2, 2, 2)
        _mw_c_sizer.Add(_mw_gen_settings, 1, wx.EXPAND, 0)

        label_1 = wx.StaticText(self._mw_controls, wx.ID_ANY, _("Output Prefix"))
        _mw_gen_settings.Add(label_1, 0, wx.ALIGN_CENTER_VERTICAL | wx.EXPAND, 0)

        self.datPrefix = wx.NewId()
        self.datPrefix = wx.TextCtrl(self._mw_controls, self.datPrefix, "")
        _mw_gen_settings.Add(self.datPrefix, 2, wx.ALIGN_CENTER_VERTICAL | wx.EXPAND, 0)

        label_2 = wx.StaticText(self._mw_controls, wx.ID_ANY, _("Frequency"))
        _mw_gen_settings.Add(label_2, 0, wx.ALIGN_CENTER_VERTICAL | wx.EXPAND, 0)

        self.spin_ctrl_1 = wx.SpinCtrl(
            self._mw_controls, wx.ID_ANY, "10", min=0, max=20
        )
        _mw_gen_settings.Add(
            self.spin_ctrl_1, 2, wx.ALIGN_CENTER_VERTICAL | wx.EXPAND, 0
        )

        _mw_gen_settings.Add((0, 0), 0, 0, 0)

        self.rotate = wx.NewId()
        self.rotate = wx.CheckBox(
            self._mw_controls, self.rotate, _("Rotate files at midnight?")
        )
        self.rotate.SetValue(1)
        _mw_gen_settings.Add(self.rotate, 2, wx.ALIGN_CENTER_VERTICAL | wx.EXPAND, 0)

        label_3 = wx.StaticText(self._mw_controls, wx.ID_ANY, _("Log level"))
        _mw_gen_settings.Add(label_3, 1, wx.ALIGN_CENTER_VERTICAL | wx.EXPAND, 0)

        self.verbose = wx.NewId()
        self.verbose = wx.SpinCtrl(self._mw_controls, self.verbose, "1", min=0, max=3)
        _mw_gen_settings.Add(self.verbose, 2, wx.ALIGN_CENTER_VERTICAL | wx.EXPAND, 0)

        _mw_c_sizer.Add((0, 10), 0, 0, 0)

        lblStateFileSettings = wx.StaticText(
            self._mw_controls, wx.ID_ANY, _("State File")
        )
        lblStateFileSettings.SetFont(
            wx.Font(
                11,
                wx.FONTFAMILY_DEFAULT,
                wx.FONTSTYLE_NORMAL,
                wx.FONTWEIGHT_BOLD,
                0,
                "",
            )
        )
        _mw_c_sizer.Add(
            lblStateFileSettings, 0, wx.ALIGN_CENTER_VERTICAL | wx.EXPAND, 0
        )

        _mw_statesettings = wx.GridSizer(2, 2, 2, 2)
        _mw_c_sizer.Add(_mw_statesettings, 1, wx.EXPAND, 0)

        self.savestate = wx.NewId()
        self.saveState = wx.CheckBox(
            self._mw_controls, self.savestate, _("Record State File")
        )
        self.saveState.SetValue(1)
        _mw_statesettings.Add(
            self.saveState, 2, wx.ALIGN_CENTER_VERTICAL | wx.EXPAND, 0
        )

        lblStatePath = wx.StaticText(self._mw_controls, wx.ID_ANY, _("State File"))
        _mw_statesettings.Add(lblStatePath, 0, wx.ALIGN_CENTER_VERTICAL | wx.EXPAND, 0)

        self.statePath = wx.NewId()
        self.statePath = wx.TextCtrl(self._mw_controls, self.statePath, "")
        _mw_statesettings.Add(
            self.statePath, 2, wx.ALIGN_CENTER_VERTICAL | wx.EXPAND, 0
        )

        _mw_c_sizer.Add((0, 25), 0, 0, 0)

        _mw_source_control = wx.GridSizer(1, 3, 2, 2)
        _mw_c_sizer.Add(_mw_source_control, 1, wx.EXPAND, 0)

        self.btnAddSource = wx.Button(self._mw_controls, wx.ID_ANY, _("&Add Source..."))
        _mw_source_control.Add(self.btnAddSource, 1, wx.ALL | wx.EXPAND, 2)

        self.btnEditSource = wx.Button(
            self._mw_controls, wx.ID_ANY, _("&Edit Source...")
        )
        _mw_source_control.Add(self.btnEditSource, 1, wx.ALL | wx.EXPAND, 2)

        self.btnRemoveSource = wx.Button(
            self._mw_controls, wx.ID_ANY, _("&Remove Source...")
        )
        _mw_source_control.Add(self.btnRemoveSource, 1, wx.ALL | wx.EXPAND, 2)

        self.helptext = wx.NewId()
        lblHelp = wx.StaticText(
            self._mw_controls,
            self.helptext,
            _(
                "Adjust the general logger settings above, then use the Add, Edit, and Remove Source buttons to define the data sources required for this configuration.\n\nWhen complete, use the Save File button at the top of the screen to export settings ready for use on the logger device."
            ),
        )
        lblHelp.Wrap(350)
        _mw_c_sizer.Add(lblHelp, 1, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 10)

        self.sourcelist = wx.grid.Grid(self._mw, wx.ID_ANY, size=(1, 1))
        self.sourcelist.CreateGrid(0, 3)
        self.sourcelist.SetRowLabelSize(0)
        self.sourcelist.EnableEditing(0)
        self.sourcelist.EnableDragRowSize(0)
        self.sourcelist.EnableDragGridSize(0)
        self.sourcelist.SetSelectionMode(wx.grid.Grid.SelectRows)
        self.sourcelist.SetColLabelValue(0, _("Tag"))
        self.sourcelist.SetColSize(0, 10)
        self.sourcelist.SetColLabelValue(1, _("Type"))
        self.sourcelist.SetColSize(1, 10)
        self.sourcelist.SetColLabelValue(2, _("Description"))
        self.sourcelist.SetColSize(2, 230)

        _mw_c_sizer.AddGrowableRow(11)
        _mw_c_sizer.AddGrowableCol(0)
        self._mw_controls.SetSizer(_mw_c_sizer)

        self._mw.SplitVertically(self._mw_controls, self.sourcelist)

        self.Layout()
        self.Centre()

        self.Bind(wx.EVT_BUTTON, lambda x: addSource(self), self.btnAddSource)
        self.Bind(wx.EVT_BUTTON, lambda x: editSource(self), self.btnEditSource)
        self.Bind(wx.EVT_BUTTON, lambda x: deleteSource(self), self.btnRemoveSource)
        # end wxGlade


# end of class SLConfigGUIMain
